# Generated by Django 3.1.4 on 2021-01-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='preis',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
