# Generated by Django 3.1.4 on 2021-02-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20210126_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpizza',
            name='amount',
        ),
    ]
