# Generated by Django 3.1.4 on 2021-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_remove_orderpizza_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizza',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
