# Generated by Django 3.1.6 on 2021-02-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_orderpizza_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(related_name='pizzas', through='pizza.OrderPizza', to='pizza.Pizza'),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_pizzas', to='pizza.order'),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_pizzas', to='pizza.pizza'),
        ),
    ]
